apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cashshuffle-ingress
  namespace: default
  annotations:
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: "nginx"
spec:
  tls:
  - hosts:
    - www.cashshuffle.com
    - cashshuffle.com
    - www.cashshuffle.org
    - cashshuffle.org
    secretName: cashshuffle-tls
  defaultBackend:
    service:
      name: cashshuffle
      port:
        number: 87
  rules:
  - host: cashshuffle.com
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: cashshuffle
            port:
              number: 87
  - host: www.cashshuffle.com
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: cashshuffle
            port:
              number: 87
  - host: cashshuffle.org
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: cashshuffle
            port:
              number: 87
  - host: www.cashshuffle.org
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: cashshuffle
            port:
              number: 87
